# Generated by Django 3.1.7 on 2021-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_pastwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastwork',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
