# Generated by Django 3.1.7 on 2021-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210303_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastwork',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastwork',
            name='tools_used',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
